spring.application.name=config-server
server.port=8888

# Git repository configuration
spring.cloud.config.server.git.uri=https://github.com/Thnjs/Bankify.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=config-files

# Eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Logging
logging.level.org.springframework.cloud.config=DEBUG